/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>

 
#ifndef _Included_Profinet
#define _Included_Profinet
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_org_openmuc_framework_driver_profinet_util_RawSocket_write(JNIEnv *env, jobject thisObj, jbyteArray profinet_data, jint data_length, jbyteArray destination_mac, string intface);

JNIEXPORT jbyteArray JNICALL Java_org_openmuc_framework_driver_profinet_util_RawSocket_read(JNIEnv *env, jobject thisObj);
 
#ifdef __cplusplus
}
#endif
#endif
